### ISSUE TITLE
Typo while importing a module in Community class

### ISSUE THREAD

**Issue by alvarofrancomartins** [rafguns/linkpred#29]
The file misc.py located in _linkpred/predictors/_ contains a typo while importing `generate_dendrogram` from the `community` package.

Line 24 reads `from community import generate_dendogram, partition_at_level` but there's a missing "r" in dendogram. 

Obs: I have installed linkpred using `pip install linkpred`

**Comment by rafguns** [comment]
Thanks! It seems this function [was renamed](https://github.com/taynaud/python-louvain/issues/6#issuecomment-288519617) in python-louvain. We have to change it of course.

Note to myself: why wasn't this caught by any unit tests in CI?

**Comment by rafguns** [comment]
Ah, I now see that this was already fixed in 2487aeef6d08cf7e118a60cc8ba5ccd203f073eb. I need to release a new version that includes this.

**Comment by rafguns** [comment]
New version 0.5.1, including this fix, now up on PyPI and just a `pip install --upgrade linkpred` away! 😊
