### ISSUE TITLE
how to explain the input file format

### ISSUE THREAD

**Issue by zhangjie1982** [rafguns/linkpred#34]
Hi,I am learning the project's code. But I don't know the labels in the input file means?
Some labels like this:
1 "Pereira, JCR"
2 "Peters, HPF"
3 "Widhalm, C"
4 "Verbeek, A"
5 "Salvador, P"

**Comment by rafguns** [comment]
The example files represent two time slices of a collaboration network, where nodes are researchers and edges represent collaborations. The files are in [Pajek format](http://mrvar.fdv.uni-lj.si/pajek/). In other words, "Pereira, JCR" etc. are names of researchers.

Does this answer your question?

**Comment by zhangjie1982** [comment]
Yes! Thank you very much!
