### ISSUE TITLE
`2a0ae94` not updated on pip repository

### ISSUE THREAD

**Issue by SamuelCano03** [rafguns/linkpred#41]
Commit `2a0ae94`  has not been updated in pip repository as shown below

![image](https://github.com/user-attachments/assets/a720ff97-c6c4-45d8-b457-bdeebeb1da6d)

It still has 2020 release.

**Comment by rafguns** [comment]
Thanks for pointing that out. I'll try to push a new release to PyPI soon.

**Comment by rafguns** [comment]
Version 0.6 is now up.
